services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: villgro
      POSTGRES_USER: villgro
      POSTGRES_PASSWORD: villgro@123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=villgro
      - DB_USER=villgro
      - DB_PASSWORD=villgro
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  pgdata: