"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "*").split(",")]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_filters",

    # Local apps
    "accounts",
    "organizations",
    "banks",
    "questionnaires",
    "assessments",
    "admin_portal",
]

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15), 
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True, 
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Villgro API",
    "DESCRIPTION": "Backend APIs for Villgro Assessment & Management",
    "VERSION": "1.0.0",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_portal.middleware.RequestResponseLoggingMiddleware', 
    'admin_portal.middleware.RequestActivityMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "NAME": os.getenv("DB_NAME", "villgro"),
        "USER": os.getenv("DB_USER", "villgro"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "CONN_MAX_AGE": 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

INSTALLED_APPS += ["whitenoise.runserver_nostatic"]
MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_ROOT = "/app/staticfiles"
STATIC_URL = "/django-static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.mailgun.org")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "postmaster@YOUR_DOMAIN.mailgun.org")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "YOUR_MAILGUN_SMTP_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@YOUR_DOMAIN")

LOG_DIR = BASE_DIR / "logs"
os.makedirs(LOG_DIR, exist_ok=True)
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

ASSESSMENT_COOLDOWN_DAYS = 180

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: True,  # stub; replace if you add real request-id context
        }
    },
    "formatters": {
        "simple": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        },
        "json": {
            "format": '{{"ts":"{asctime}","lvl":"{levelname}","logger":"{name}","msg":"{message}"}}',
            "style": "{",
        },
        "access": {  # for request/response lines
            "format": "[{levelname}] {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        # Console (keep for dev)
        "console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },

        # --- Django core logs ---
        "django_file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "django.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "formatter": "json",
        },
        "django_request_file": {
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "django_request.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "formatter": "json",
        },

        # --- App-specific logs ---
        "assessments_file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "assessments.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "formatter": "json",
        },
        "accounts_file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "accounts.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "formatter": "json",
        },
        "admin_portal_file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "admin_portal.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "formatter": "json",
        },
        "banks_file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "banks.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "formatter": "json",
        },
        "organizations_file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "organizations.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "formatter": "json",
        },
        "questionnaires_file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "questionnaires.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "formatter": "json",
        },
        "emails_file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "notifications.log"),
            "maxBytes": 5_000_000,
            "backupCount": 5,
            "formatter": "json",
        },

        # --- Request/Response audit log ---
        "request_response_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "request_response.log"),
            "maxBytes": 10_000_000,
            "backupCount": 10,
            "formatter": "access",
        },
    },
    "loggers": {
        # Django
        "django": {
            "handlers": ["django_file", "console"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
        "django.request": {
            "handlers": ["django_request_file", "console"],
            "level": "WARNING",
            "propagate": False,
        },

        # apps
        "assessments": {"handlers": ["assessments_file", "console"], "level": LOG_LEVEL, "propagate": False},
        "accounts": {"handlers": ["accounts_file", "console"], "level": LOG_LEVEL, "propagate": False},
        "admin_portal": {"handlers": ["admin_portal_file", "console"], "level": LOG_LEVEL, "propagate": False},
        "banks": {"handlers": ["banks_file", "console"], "level": LOG_LEVEL, "propagate": False},
        "organizations": {"handlers": ["organizations_file", "console"], "level": LOG_LEVEL, "propagate": False},
        "questionnaires": {"handlers": ["questionnaires_file", "console"], "level": LOG_LEVEL, "propagate": False},
        "notifications": {"handlers": ["emails_file", "console"], "level": LOG_LEVEL, "propagate": False},

        # Request/Response audit channel (used by middleware)
        "http.audit": {"handlers": ["request_response_file"], "level": "INFO", "propagate": False},
    },
}
